### ISSUE TITLE
Some elements cannot be deselected

### ISSUE THREAD

**Issue by lme-nca** [wurstbrot/DevSecOps-MaturityModel#92]
The following 3 measures cannot be deselected and always show as selected in the model: 
![image](https://user-images.githubusercontent.com/79927042/134001976-6c8310b6-19ac-4fcf-b8fe-405db05c0c44.png)

Furthermore the following call leads to an exception:
http://localhost/spiderwebData.php?element=Building%20and%20testing%20of%20artifacts%20in%20virtual%20environments 

"
Warning: Undefined array key 0 in /var/www/html/spiderwebData.php on line 164

Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/spiderwebData.php:164 Stack trace: #0 /var/www/html/spiderwebData.php(164): array_keys(NULL) #1 {main} thrown in /var/www/html/spiderwebData.php on line 164
"

**Comment by wurstbrot** [comment]
Hi @lme-nca,
regarding 1: Did you try to perform `chmod +x selectedData.csv` to make sure the update can be stored?
regarding 2: Does a _selectedData.csv_ in the application exists?

**Comment by lme-nca** [comment]
Hi thx for the quick response!
Im running it locally through docker and pulling the image from dockerhub. There is a file called selectedData.csv in the root of the application. Here is a screenshot from a clean start of the application before and after I deselected all elements on the page:

![image](https://user-images.githubusercontent.com/79927042/134021126-98c4e9d7-1a01-4ece-8dd3-ee184353d3d1.png)

**Comment by lme-nca** [comment]
I get similar behavior on your own webpage: https://dsomm.timo-pagel.de/spiderweb.php

**Comment by wurstbrot** [comment]
Hi @lme-nca,
I fixed it. It is working for you now?

**Comment by lme-nca** [comment]
So this seems to fix the problem with the exception in the response for the "virtual environments" call. However I still have the problem that deselecting "Defined build process" and "Regular security training of security champions" does not result in the elements disappearing from the matrix visualization.

Even if I manually remove all elements in the selectedData.csv file:
![image](https://user-images.githubusercontent.com/79927042/134681851-f08f6923-ccfa-4bee-8553-ba3cb8f99ee6.png)

they still get displayed:
![image](https://user-images.githubusercontent.com/79927042/134681914-3e9214a8-715e-4bad-84b6-34a68db6b25c.png)

**Comment by wurstbrot** [comment]
sorry, solved.
There is a new feature to add "evidence" to the yaml. I added evidence beforehand and it enforced it to be marked as performed.
Fix: https://github.com/wurstbrot/DevSecOps-MaturityModel/commit/a608f7d28cc10fcd28262c1a1397e771972e7d95

**Comment by lme-nca** [comment]
Hi @wurstbrot, thx for the fix! it is all working as expected now!
